on:
  workflow_dispatch:

jobs:
  refresh-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6.0.0
      
      - name: Install dependencies with pip
        run: pip3 install gseapy requests mygene
      - name: check ls
        run: ls
      - name: Run preprocessing
        
        run: |
          python3 wikipathways/wp.py
 
